[workspace]
resolver = "2"
members = [
    "enlil-platform",
    "enlil-hal",
    "enlil-core",
    "enlil-devices",
    "enlil-config",
    "enlil-mgmt",
    "enlil-boot",
    "enlil-setup",
    "enlil-std",
]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
toml = "0.8"
anyhow = "1"
thiserror = "2"
log = "0.4"
clap = { version = "4", features = ["derive"] }
