//! BadAML-style AML fuzz regression tests.
//!
//! Guests parse the AML this crate synthesizes; malformed-table handling is
//! fuzzed here so a guest-visible ACPI bug is caught before 1.0. This is the
//! deterministic, CI-friendly half of T-5.3:
//!
//! * the checked-in corpus (`fuzz/corpus/aml/`, generated by
//!   `examples/gen_aml_corpus.rs`) is classified: `valid_*` seeds must validate
//!   clean, `malformed_*` seeds must be rejected — neither may ever panic;
//! * a seeded PRNG mutation campaign (bit flips, truncations, splices, …) hammers
//!   the validator the way libFuzzer would, asserting totality: every input
//!   returns `Ok`/`Err`, never panics, never hangs;
//! * a builder config matrix proves the tables we actually ship always validate.
//!
//! The nondeterministic half is the libFuzzer target
//! (`fuzz/fuzz_targets/aml.rs`): `cargo fuzz run aml`.

use std::path::PathBuf;

use enlil_devices::acpi::aml_validate::{AmlError, validate_aml, validate_table_payload};
use enlil_devices::acpi::dsdt::{DsdtBuilder, DsdtConfig};
use enlil_devices::acpi::ssdt::SsdtBuilder;

fn corpus_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../fuzz/corpus/aml")
}

fn read_seed(name: &str) -> Vec<u8> {
    let path = corpus_dir().join(name);
    std::fs::read(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()))
}

fn valid_seeds() -> Vec<(String, Vec<u8>)> {
    let mut seeds = Vec::new();
    let entries = std::fs::read_dir(corpus_dir()).expect("read corpus dir");
    for entry in entries {
        let entry = entry.expect("corpus entry");
        let name = entry.file_name().to_string_lossy().into_owned();
        if name.starts_with("valid_") {
            seeds.push((name.clone(), read_seed(&name)));
        }
    }
    assert!(!seeds.is_empty(), "no valid_* seeds in corpus");
    seeds.sort_by(|a, b| a.0.cmp(&b.0));
    seeds
}

fn malformed_seeds() -> Vec<(String, Vec<u8>)> {
    let mut seeds = Vec::new();
    let entries = std::fs::read_dir(corpus_dir()).expect("read corpus dir");
    for entry in entries {
        let entry = entry.expect("corpus entry");
        let name = entry.file_name().to_string_lossy().into_owned();
        if name.starts_with("malformed_") {
            seeds.push((name.clone(), read_seed(&name)));
        }
    }
    assert!(!seeds.is_empty(), "no malformed_* seeds in corpus");
    seeds.sort_by(|a, b| a.0.cmp(&b.0));
    seeds
}

/// Every `valid_*` corpus seed is real builder output and must validate clean.
#[test]
fn acpi_corpus_valid_seeds_validate_clean() {
    for (name, bytes) in valid_seeds() {
        assert_eq!(
            validate_aml(&bytes),
            Ok(()),
            "valid seed {name} rejected — builder or validator regression"
        );
    }
}

/// Every `malformed_*` seed must be rejected — and rejection must never panic,
/// via either entry point.
#[test]
fn acpi_corpus_malformed_seeds_rejected_without_panic() {
    for (name, bytes) in malformed_seeds() {
        let result = validate_aml(&bytes);
        assert!(
            result.is_err(),
            "malformed seed {name} unexpectedly accepted: validator too lax"
        );
        // The whole-table entry point must also be total on hostile input.
        let _ = validate_table_payload(&bytes);
    }
}

/// The tables we actually ship — DSDT/SSDT across a config matrix — must always
/// validate, both as raw AML and as whole tables (header length + checksum).
#[test]
fn acpi_generated_tables_validate_clean() {
    // DSDT: vCPU counts × optional-device toggles.
    for vcpus in [1u8, 2, 4, 8] {
        for (hpet, rtc, ps2) in [
            (true, true, true),
            (false, false, false),
            (true, false, true),
        ] {
            let table = DsdtBuilder::new(DsdtConfig {
                vcpu_count: vcpus,
                has_hpet: hpet,
                has_rtc: rtc,
                has_ps2: ps2,
                ..DsdtConfig::default()
            })
            .build();
            assert_eq!(
                validate_table_payload(&table),
                Ok(()),
                "DSDT rejected (vcpus={vcpus}, hpet={hpet}, rtc={rtc}, ps2={ps2})"
            );
            assert_eq!(
                validate_aml(&table[36..]),
                Ok(()),
                "DSDT AML payload rejected (vcpus={vcpus})"
            );
        }
    }
    // SSDT: vCPU counts, default and empty power-state tables.
    for vcpus in [1u8, 2, 4, 8, 16] {
        let table = SsdtBuilder::new(vcpus).build();
        assert_eq!(
            validate_table_payload(&table),
            Ok(()),
            "SSDT rejected (vcpus={vcpus})"
        );
        let bare = SsdtBuilder::new(vcpus)
            .pstates(Vec::new())
            .cstates(Vec::new())
            .build();
        assert_eq!(
            validate_table_payload(&bare),
            Ok(()),
            "bare SSDT rejected (vcpus={vcpus})"
        );
    }
}

/// Deterministic xorshift64* PRNG: the campaign is reproducible run to run.
struct Rng(u64);

impl Rng {
    fn next(&mut self) -> u64 {
        // xorshift64*
        let mut x = self.0;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.0 = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }

    fn below(&mut self, n: usize) -> usize {
        (self.next() % n as u64) as usize
    }
}

/// Apply one random structural mutation, BadAML-style.
fn mutate(rng: &mut Rng, bytes: &[u8], other: &[u8]) -> Vec<u8> {
    let mut out = bytes.to_vec();
    if out.is_empty() {
        out.push(rng.next() as u8);
        return out;
    }
    match rng.below(6) {
        // Flip a random bit.
        0 => {
            let i = rng.below(out.len());
            out[i] ^= 1 << rng.below(8);
        }
        // Set a random byte to a random value.
        1 => {
            let i = rng.below(out.len());
            out[i] = rng.next() as u8;
        }
        // Truncate at a random point (never to empty — that stays valid).
        2 => {
            let i = 1 + rng.below(out.len());
            out.truncate(i);
        }
        // Insert a random byte at a random position.
        3 => {
            let i = rng.below(out.len() + 1);
            out.insert(i, rng.next() as u8);
        }
        // Splice in a chunk from another seed.
        4 if !other.is_empty() => {
            let src = rng.below(other.len());
            let len = 1 + rng.below((other.len() - src).min(16));
            let dst = rng.below(out.len() + 1);
            out.splice(dst..dst, other[src..src + len].iter().copied());
        }
        // Duplicate a chunk in place.
        _ => {
            let src = rng.below(out.len());
            let len = 1 + rng.below((out.len() - src).min(16));
            let chunk = out[src..src + len].to_vec();
            out.splice(src..src, chunk);
        }
    }
    out
}

/// Deterministic mutation campaign over the whole corpus: the validator must be
/// total — every mutated input returns `Ok` or `Err`, never panics, never hangs.
/// (A panic here fails the test, which is exactly the signal we want: it means
/// the validator is not total and the fuzzer would have found a crash.)
#[test]
fn acpi_deterministic_mutation_campaign_never_panics() {
    let valids = valid_seeds();
    let mut rng = Rng(0x0BAD_A15E_ED42);
    let mut iterations = 0usize;
    let mut rejected = 0usize;
    // Keep the campaign fast enough for CI: a few thousand mutations per seed,
    // each a linear walk over a few KiB.
    const PER_SEED: usize = 2_000;
    for (idx, (_name, seed)) in valids.iter().enumerate() {
        let other = &valids[(idx + 1) % valids.len()].1;
        for _ in 0..PER_SEED {
            let mutated = mutate(&mut rng, seed, other);
            let result = validate_aml(&mutated);
            iterations += 1;
            if result.is_err() {
                rejected += 1;
            }
            // The whole-table entry point gets the same treatment on a sample.
            if iterations.is_multiple_of(7) {
                let _ = validate_table_payload(&mutated);
            }
        }
    }
    assert!(iterations > 0, "campaign ran zero iterations");
    // Sanity: mutations must actually break structure sometimes — a validator
    // that accepts everything is not validating.
    assert!(
        rejected > iterations / 10,
        "only {rejected}/{iterations} mutations rejected — validator looks vacuous"
    );
    println!("BadAML campaign: {iterations} mutations, {rejected} rejected, 0 panics");
}

/// Spot-check that specific hostile shapes map to the expected error kinds.
/// These pin the validator's classification so a future loosening is visible.
#[test]
fn acpi_hostile_shapes_classify_as_expected() {
    // Truncated mid-name.
    assert_eq!(
        validate_aml(&[0x10, 0x03, b'_', b'S']),
        Err(AmlError::Truncated)
    );
    // PkgLength overrun.
    assert_eq!(
        validate_aml(&[0x10, 0xFF, 0xFF, 0xFF, 0xFF]),
        Err(AmlError::PkgLengthOverrun)
    );
    // Digit-leading NameSeg.
    assert_eq!(
        validate_aml(&[0x08, b'1', b'A', b'B', b'C', 0x00]),
        Err(AmlError::InvalidName)
    );
    // Unknown opcode.
    assert_eq!(validate_aml(&[0xFF]), Err(AmlError::UnknownOpcode(0xFF)));
    // Buffer size lie.
    assert_eq!(
        validate_aml(&[0x11, 0x04, 0x0A, 0x02, 0xAA]),
        Err(AmlError::BufferSizeMismatch)
    );
    // Whole-table length lie.
    let mut table = vec![0u8; 40];
    table[0..4].copy_from_slice(b"DSDT");
    assert_eq!(
        validate_table_payload(&table),
        Err(AmlError::TableLengthMismatch)
    );
}
